version: '3'
services:
  app:
    container_name: restapi
    restart: always
    build: .
    ports:
      - '3000:3000'
    external_links:
      - mongo
      - mosquitto
  mongo:
    container_name: mongo
    command: 
      - '--logpath'
      - '/var/log/mongodb/mongod.log'
    image: mongo
    ports:
      - '27017:27017'
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:2
    volumes:
      - ./config/:/mosquitto/config/:rw
      - ./log/:/mosquitto/log/
      - data:/mosquitto/data/
    ports:
      - '1884:1884'

volumes:
  data: ~