version: '3'
services:
  app:
    container_name: smart-lock
    restart: always
    # env_file: ./.env
    image: raghavendiran2002/smart-home-docker:latest
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
    #   - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - '3000:3000'
    links:
      - mqtt
      - mongodb
    depends_on:
      - mongodb
      - mqtt


  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto:latest
    volumes:
      - ./config/:/mosquitto/config/:rw
      # - ./log/:/mosquitto/log/
      # - data:/mosquitto/data/
    ports:
      - 1885:1883

  mongodb:
    container_name: mongodb
    image: mongo:6.0.3
    # volumes:
    #   - ~/mongo:/data/db
    ports:
      - "27015:27017"
# volumes:
#   data: ~